### ISSUE TITLE
How to output the  4-by-3 maps from the depth layers?

### ISSUE THREAD

**Issue by liyongrui** [piiswrong/deep3d#36]
Can you give me some codes about that? My ability is so poor that I can't find the way to output these maps. I try to output these maps from the deconvolution which is behind some pooling layer, but I failed, I can't find the way to output some values such as pred1, pred2, and so on in sym.py from the module. I just want the method or codes of the output of the 4-by-3 maps from the depth layers in your paper. Can you help me? Thank you.

**Comment by liyongrui** [comment]
aha! I have solved this problem! Read this paper carefully! How stupid I am!

**Comment by n1ckfg** [comment]
What's the solution?

**Comment by liyongrui** [comment]
save the model of "softmaxActivition", and output it .So easy.....TT

**Comment by n1ckfg** [comment]
Awesome, thanks!
