### ISSUE TITLE
I want images larger than 384x160

### ISSUE THREAD

**Issue by tzatter** [piiswrong/deep3d#8]
I have got an error when I used raw_shape instead of shape as below code

shape = (384, 160)
img = cv2.imread('demo.jpg')
raw_shape = (img.shape[1], img.shape[0])
# img = cv2.resize(img, shape)

img = cv2.resize(img, raw_shape)

Thank you piiswrong

**Comment by tzatter** [comment]
I am sorry, This is not issue
I can't wait to release the training code!

**Comment by zedomel** [comment]
Could you get images larger than 384x160??? I'm using the train code, but I have got errors when change shape size in python files. How can I change the dimensions? 
thanks
